
import tkinter as tk
root= tk.Tk()
root.title("login page")
root.geometry("500x500")
login=tk.Button(text="log in")
name_label=tk.Label (root,text="name")
name_entry=tk.Entry(root)
password_label=tk.Label(root,text="password")
password_entry=tk.Entry(root)
name_label.grid(row=0,column=0)
password_label.grid(row=1,column=0)
name_entry.grid(row=0,column=1)
password_entry.grid(row=1,column=1)
login.grid(row=3,column=0)
def newwindow_2():
    time_label=tk.Label(text="enter u r distance in km")
    number_label=tk.Label(text="enter u r number")
    number_entry=tk.Entry(root)
    number_label.grid(row=1,column=0)
    number_entry.grid(row=1,column=1)
    time_label.grid(row=0,column=0)
    time_entry=tk.Entry(root)
    time_entry.grid(row=0,column=1)
    a=time_entry.get()
    cost=tk.Label(text="this i su r cost",)
    cost.grid(row=5,column=1)
    time_entry.grid(row=0,column=1)
    next=tk.Button(text="next step")
    next.grid(row=3,column=0)
def fun():
   password=password_entry.get()
   name=name_entry.get()
   if(name==""and password==""): 
     root= tk.Tk()
     root.title(" enter name")
     root.geometry("500x500")
     nam_label=tk.Label (root,text="enter ur name and password").grid(row=1,column=1)
   elif(name==""):
     root= tk.Tk()
     root.title("enter name")
     root.geometry("500x500")
     pass_label=tk.Label (root,text="enter ur name").grid(row=1,column=1)
      
   elif(password==""):
     root= tk.Tk()
     root.title("enter password")
     root.geometry("500x500")
     pass_label=tk.Label (root,text="enter ur password").grid(row=1,column=1)
   else:
     root=tk.Tk()
     root.title("destination")
     root.geometry("500x500")
     next=tk.Button(text="next step")
     next.grid(row=4,column=0)
     from_label=tk.Label(root,text="pickup point")
     from_entry=tk.Entry(root)
     to_label=tk.Label(root,text="drop point")
     to_entry=tk.Entry(root)
     from_label.grid(row=0,column=0)
     from_entry.grid(row=0,column=1)
     to_label.grid(row=1,column=0)
     to_entry.grid(row=1,column=1)
     def drop():
      pickup=from_entry.get()
      drop=to_entry.get()
      if(pickup==""and drop==""): 
       root= tk.Tk()
       root.title(" enter correctly")
       root.geometry("500x500")
       pic_label=tk.Label (root,text="enter pickup point and drop point").grid(row=1,column=1)
      elif(pickup==""):
       root= tk.Tk()
       root.title("enter name")
       root.geometry("500x500")
       pick_label=tk.Label (root,text="enter pickup point").grid(row=1,column=1)     
      elif(drop==""):
       root= tk.Tk()
       root.title("enter password")
       root.geometry("500x500")
       dro_label=tk.Label (root,text="enter drop point").grid(row=1,column=1)
     next.config(command=drop)
login.config(command=fun)
root.mainloop()

