import tkinter as tk
root=tk.Tk()
name_label=tk.Label(text="name")
name_label.grid(row=0,column=0)
name_entry=tk.Entry(root)
name_entry.grid(row=0,column=1)
age_label=tk.Label(text="age")
age_label.grid(row=1,column=0)
age_entry=tk.Entry(root)
age_entry.grid(row=1,column=1)
save_button=tk.Button(text="save")
save_button.grid(row=2,column=1)
def fun():
    name=name_entry.get()
    age=age_entry.get()
    import mysql.connector
    data=mysql.connector.connect(host='localhost', user='root',password = '',database='lksql',)
    mycursor=data.cursor()
    sql = 'INSERT INTO data (name,age) VALUES (%s,%s)'
    val = (name,age)
    mycursor.execute(sql,val)
    data.commit()
    print(mycursor.rowcount,'records affected')
    dept_label=tk.Label(text="dept")
    dept_label.grid(row=0,column=0)
    dept_entry=tk.Entry(root)
    dept_entry.grid(row=0,column=1)
    gender_label=tk.Label(text="gender")
    gender_label.grid(row=1,column=0)
    gender_entry=tk.Entry(root)
    gender_entry.grid(row=0,column=1)
    data=(dept_entry.get(),gender_entry.get())
    #next_button=tk.Button(text="save")
    #next_button.grid(row=2,column=1)
    #next_button.config(commanad=fun)
    import mysql.connector
    data=mysql.connector.connect(host='localhost', user='root',password = '',database='lksql',) 
    mycursor=data.cursor()
    mycursor.execute("UPDATE student SET dept=%s,gender=%s, WHERE id=1",data)
    data.commit()
save_button.config(command=fun)
root.mainloop 
